<select name="timezone" id="timezone" class="form-control placeholder-no-fix">
	<option value="" selected="selected">Select your timezone</option>
	<option value="Pacific/Midway | -11">(-11:00) Midway Island, Samoa</option>
	<option value="Pacific/Honolulu | -10">(-10:00) Hawaii</option>
	<option value="America/Adak | -10">(-10:00) Aleutian-Adak</option>
	<option value="Pacific/Gambier | -09">(-09:00) Gambier Islands</option>
	<option value="America/Anchorage| | -09">(-09:00) Alaska</option>
	<option value="America/Los_Angeles | -08">(-08:00) Pacific Time (US &amp; Canada)</option>
	<option value="America/Ensenada | -08">(-08:00) Tijuana, Baja California</option>
	<option value="America/Denver | -07">(-07:00) Mountain Time (US &amp; Canada)</option>
	<option value="America/Chihuahua | -07">(-07:00) Chihuahua, La Paz, Mazatlan</option>
	<option value="America/Dawson_Creek | -07">(-07:00) Arizona</option>
	<option value="America/Chicago | -06">(-06:00) Central Time (US &amp; Canada)</option>
	<option value="America/Belize | -06">(-06:00) Saskatchewan, Central America</option>
	<option value="America/Cancun | -06">(-06:00) Guadalajara, Mexico City, Monterrey</option>
	<option value="Chile/EasterIsland | -06">(-06:00) Easter Island</option>
	<option value="America/New_York | -05">(-05:00) Eastern Time (US &amp; Canada)</option>
	<option value="America/Havana | -05" >(-05:00) Cuba</option>
	<option value="America/Bogota | -05">(-05:00) Bogota, Lima, Quito, Rio Branco</option>
	<option value="America/Santiago | -04">(-04:00) Santiago</option>
	<option value="America/La_Paz | -04">(-04:00) La Paz</option>
	<option value="Atlantic/Stanley | -04">(-04:00) Faukland Islands</option>
	<option value="America/Campo_Grande | -04">(-04:00) Brazil</option>
	<option value="America/Goose_Bay | -04">(-04:00) Atlantic Time (Goose Bay)</option>
	<option value="America/Glace_Bay | -04">(-04:00) Atlantic Time (Canada)</option>
	<option value="America/Araguaina | -03">(-03:00) UTC-3</option>
	<option value="America/Montevideo | -03">(-03:00) Montevideo</option>
	<option value="America/Miquelon | -03">(-03:00) Miquelon, St. Pierre</option>
	<option value="America/Godthab | -03">(-03:00) Greenland</option>
	<option value="America/Argentina/Buenos_Aires | -03">(-03:00) Buenos Aires</option>
	<option value="America/Sao_Paulo | -03">(-03:00) Brasilia</option>
	<option value="America/Noronha | -02">(-02:00) Mid-Atlantic</option>
	<option value="Atlantic/Cape_Verde | -01">(-01:00) Cape Verde Is.</option>
	<option value="Atlantic/Azores | -01">(-01:00) Azores</option>
	<option value="GMT | +00">(00:00) Greenwich Mean Time</option>
	<option value="Europe/Belfast | +00">(00:00) Greenwich Mean Time : Belfast</option>
	<option value="Europe/Dublin | +00">(00:00) Greenwich Mean Time : Dublin</option>
	<option value="Europe/Lisbon | +00">(00:00) Greenwich Mean Time : Lisbon</option>
	<option value="Europe/London | +00">(00:00) Greenwich Mean Time : London</option>
	<option value="Africa/Abidjan | +00">(00:00) Monrovia, Reykjavik</option>
	<option value="Europe/Amsterdam | +01">(+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna</option>
	<option value="Europe/Belgrade | +01">(+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague</option>
	<option value="Europe/Brussels | +01">(+01:00) Brussels, Copenhagen, Madrid, Paris</option>
	<option value="Africa/Algiers | +01">(+01:00) West Central Africa</option>
	<option value="Africa/Windhoek | +01">(+01:00) Windhoek</option>
	<option value="Europe/Istanbul | +02">(+02:00) Istanbul</option>
	<option value="Europe/Helsinki | +02">(+02:00) Helsinki</option>
	<option value="Asia/Beirut | +02">(+02:00) Beirut</option>
	<option value="Africa/Cairo | +02">(+02:00) Cairo</option>
	<option value="Africa/Johannesburg | +02">(+02:00) Johannesburg, Pretoria</option>
	<option value="Asia/Gaza | +02">(+02:00) Gaza</option>
	<option value="Asia/Jerusalem | +02">(+02:00) Jerusalem</option>
	<option value="Europe/Kiev | +02">(+02:00) Kiev</option>
	<option value="Europe/Minsk | +02">(+02:00) Minsk</option>
	<option value="Asia/Damascus | +02">(+02:00) Syria</option>
	<option value="Africa/Addis_Ababa | +03">(+03:00) Nairobi</option>
	<option value="Europe/Moscow | +03">(+03:00) Moscow, St. Petersburg, Volgograd</option>
	<option value="Asia/Dubai | +04">(+04:00) Abu Dhabi, Muscat</option>
	<option value="Asia/Yerevan | +04">(+04:00) Yerevan</option>
	<option value="Asia/Yekaterinburg | +05">(+05:00) Ekaterinburg</option>
	<option value="Asia/Tashkent | +05">(+05:00) Tashkent</option>
	<option value="Asia/Karachi | +05">(+05:00) Islamabad, Karachi, Pakistan</option>
	<option value="Asia/Dhaka | +06">(+06:00) Astana, Dhaka</option>
	<option value="Asia/Novosibirsk | +06">(+06:00) Novosibirsk</option>
	<option value="Asia/Bangkok | +07">(+07:00) Bangkok, Hanoi, Jakarta</option>
	<option value="Asia/Krasnoyarsk | +07">(+07:00) Krasnoyarsk</option>
	<option value="Asia/Hong_Kong | +08">(+08:00) Beijing, Chongqing, Hong Kong, Urumqi</option>
	<option value="Asia/Irkutsk | +08">(+08:00) Irkutsk, Ulaan Bataar</option>
	<option value="Australia/Perth | +08">(+08:00) Perth</option>
	<option value="Asia/Tokyo | +09">(+09:00) Osaka, Sapporo, Tokyo</option>
	<option value="Asia/Seoul | +09">(+09:00) Seoul</option>
	<option value="Asia/Yakutsk | +09">(+09:00) Yakutsk</option>
	<option value="Australia/Melbourne | +10">(+10:00) Melbourne</option>
	<option value="Australia/Brisbane | +10">(+10:00) Brisbane</option>
	<option value="Australia/Hobart | +10">(+10:00) Hobart</option>
	<option value="Asia/Vladivostok | +10">(+10:00) Vladivostok</option>
	<option value="Etc/GMT-11 | +11">(+11:00) Solomon Is., New Caledonia</option>
	<option value="Asia/Magadan | +11">(+11:00) Magadan</option>
	<option value="Asia/Anadyr | +12">(+12:00) Anadyr, Kamchatka</option>
	<option value="Pacific/Auckland | +12">(+12:00) Auckland, Wellington</option>
	<option value="Etc/GMT-12 | +12">(+12:00) Fiji, Kamchatka, Marshall Is.</option>
	<option value="Pacific/Tongatapu | +13">(+13:00) Nuku'alofa</option>
	<option value="Pacific/Kiritimati | +14">(+14:00) Kiritimati</option>
</select>